export const text = [
  "Theres all this spanish text on my site give us a complimentary logo along with the website. Can you make it more infographic-y the hair is just too polarising, or try a more powerful colour, or I want you to take it to the next level this is just a 5 minutes job i'll pay you in a week we don't need to pay upfront i hope you understand. Can we try some other colours maybe can the black be darker. This looks perfect. Just Photoshop out the dog, add a baby, and make the curtains blue we are your relatives, yet we need more images of groups of people having non-specific types of fun.",
  "That's great, but can you make it work for ie 2 please we need to make the new version clean and sexy this was not according to brief, and try making it a bit less blah nor could you move it a tad to the left low resolution? It looks ok on my screen can we have another option. Concept is bang on, but can we look at a better execution make the font bigger could you solutionize that for me, or this looks perfect. Just Photoshop out the dog, add a baby, and make the curtains blue in an ideal world or make the font bigger yet I think we need to start from scratch. We are a non-profit organization you are lucky to even be doing this for us, but mmm, exactly like that, but different we don't need a backup, it never goes down! can you make the font bigger?, and can you use a high definition screenshot make it pop.",
  "We exceed the clients' expectations we try your eye, but can you change everything?. That will be a conversation piece other agencies charge much lesser, so i cant pay you , we don't need a backup, it never goes down! can you please change the color theme of the website to pink and purple? make the logo a bit smaller because the logo is too big can you link the icons to my social media accounts? oh and please put pictures of cats everywhere, you might wanna give it another shot.",
  "We need to make the new version clean and sexy we don't need a contract, do we i was wondering if my cat could be placed over the logo in the flyer can you please send me the design specs again? try a more powerful colour, nor pass the mayo, appeal to the client, sue the vice president I have printed it out, but the animated gif is not moving.",
  "Can you make it look more designed can you make it more infographic-y we exceed the clients' expectations or that will be a conversation piece make it pop and can you make it look like this clipart i found. There is too much white space could you solutionize that for me. That will be a conversation piece remember, everything is the same or better it needs to be the same, but totally different for I have an awesome idea for a startup, i need you to build it for me. Can you make it faster?.",
  "It looks a bit empty, try to make everything bigger this looks perfect. Just Photoshop out the dog, add a baby, and make the curtains blue we are a non-profit organization. You might wanna give it another shot you are lucky to even be doing this for us nor can you help me out? you will get a lot of free exposure doing this. I'll know it when i see it this red is too red nor can you make pink a little more pinkish, and use a kpop logo that's not a kpop logo! ugh.",
  "Theres all this spanish text on my site i cant pay you thats not what i saw in my head at all for submit your meaningless business jargon to be used on the site!, we need more images of groups of people having non-specific types of fun it looks a bit empty, try to make everything bigger. Doing some work for us 'pro bono' will really add to your portfolio i promise this red is too red.",
  "We don't need a backup, it never goes down! can you lower the price for the website? make it high quality and please use html can you make the font a bit bigger and change it to times new roman? jazz it up a little bit make the picture of the cupcake look delicious make the purple more well, purple-er it looks so empty add some more hearts can you add a bit of pastel pink and baby blue because the purple alone looks too fancy okay can you put a cute quote on the right side of the site?",
  "That's going to be a chunk of change make it original thanks for taking the time to make the website, but i already made it in wix, im not sure, try something else can you punch up the fun level on these icons yet make it look like Apple, for that's great, but can you make it work for ie 2 please. Can you please change the color theme of the website to pink and purple? make the logo a bit smaller because the logo is too big can you link the icons to my social media accounts?",
  "We need more images of groups of people having non-specific types of fun can you make it look more designed but I need a website. How much will it cost can you make it look more designed i was wondering if my cat could be placed over the logo in the flyer can you make it look more designed . Can you rework to make the pizza look more delicious. Can you make it more infographic-y remember, everything is the same or better but there are more projects lined up charge extra the next time can the black be darker i'll know it when i see it, or use a kpop logo that's not a kpop logo! ugh can you lower the price for the website?",
];
